#!/usr/bin/env python3
"""
viz_scene.py

Visualize a full SQ+primitive scene generated by generate_sq_scene.py.

Expected directory structure:
    <scene_dir>/
        coord.npy   (N, 3) float32
        normal.npy  (N, 3) float32
        color.npy   (N, 3) uint8

Usage examples:

    python viz_scene.py --scene-dir data/test_scene_mix

    # Color by normals instead of stored RGB, and hide arrows
    python viz_scene.py --scene-dir data/test_scene_mix --color-by-normals --no-arrows
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401


def load_scene_arrays(scene_dir: Path):
    coord_path = scene_dir / "coord.npy"
    normal_path = scene_dir / "normal.npy"
    color_path = scene_dir / "color.npy"

    if not coord_path.is_file():
        raise FileNotFoundError(f"Missing coord.npy in {scene_dir}")
    if not normal_path.is_file():
        raise FileNotFoundError(f"Missing normal.npy in {scene_dir}")
    if not color_path.is_file():
        raise FileNotFoundError(f"Missing color.npy in {scene_dir}")

    xyz = np.load(coord_path)   # (N, 3)
    nrm = np.load(normal_path)  # (N, 3)
    rgb = np.load(color_path)   # (N, 3), uint8

    return xyz, nrm, rgb


def visualize_scene(
    xyz: np.ndarray,
    nrm: np.ndarray,
    rgb: np.ndarray,
    *,
    color_by_normals: bool = False,
    show_arrows: bool = True,
    max_arrows: int = 1000,
):
    """
    xyz: (N, 3)
    nrm: (N, 3)
    rgb: (N, 3), uint8
    """
    N = xyz.shape[0]

    # Colors
    if color_by_normals:
        # map normals in [-1,1] to [0,1] for RGB
        n = nrm / (np.linalg.norm(nrm, axis=1, keepdims=True) + 1e-9)
        colors = 0.5 * (n + 1.0)
    else:
        colors = rgb.astype(np.float32) / 255.0

    # Subsample for arrows
    if show_arrows:
        if max_arrows is not None and N > max_arrows:
            idx_arrow = np.random.choice(N, size=max_arrows, replace=False)
        else:
            idx_arrow = np.arange(N)
        pts_arrow = xyz[idx_arrow]
        nrm_arrow = nrm[idx_arrow]
    else:
        pts_arrow = None
        nrm_arrow = None

    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    ax.scatter(
        xyz[:, 0],
        xyz[:, 1],
        xyz[:, 2],
        s=1,
        alpha=0.6,
        depthshade=False,
        c=colors,
    )

    # Compute bbox for scaling / arrow length
    bbox_min = xyz.min(axis=0)
    bbox_max = xyz.max(axis=0)
    bbox_size = bbox_max - bbox_min
    max_range = bbox_size.max()
    mid = (bbox_min + bbox_max) / 2.0

    if show_arrows and pts_arrow is not None and pts_arrow.shape[0] > 0:
        arrow_length = max_range * 0.05  # smaller than in per-object view
        ax.quiver(
            pts_arrow[:, 0],
            pts_arrow[:, 1],
            pts_arrow[:, 2],
            nrm_arrow[:, 0],
            nrm_arrow[:, 1],
            nrm_arrow[:, 2],
            length=arrow_length,
            normalize=True,
            linewidth=0.4,
        )

    # Equal aspect ratio
    for setter, m in zip((ax.set_xlim, ax.set_ylim, ax.set_zlim), mid):
        setter(m - max_range / 2.0, m + max_range / 2.0)

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    title = "SQ+Primitive Scene"
    if color_by_normals:
        title += " (colored by normals)"
    ax.set_title(title)

    plt.tight_layout()
    plt.show()


def main():
    parser = argparse.ArgumentParser(description="Visualize a full SQ+primitive scene.")
    parser.add_argument(
        "--scene-dir",
        type=str,
        required=True,
        help="Directory containing coord.npy, normal.npy, color.npy.",
    )
    parser.add_argument(
        "--color-by-normals",
        action="store_true",
        help="Color points by normal direction instead of stored RGB.",
    )
    parser.add_argument(
        "--no-arrows",
        action="store_true",
        help="Disable drawing normal arrows.",
    )
    parser.add_argument(
        "--max-arrows",
        type=int,
        default=1000,
        help="Maximum number of normals to visualize as arrows.",
    )

    args = parser.parse_args()
    scene_dir = Path(args.scene_dir)

    xyz, nrm, rgb = load_scene_arrays(scene_dir)
    print(f"[INFO] Loaded scene from {scene_dir}: N={xyz.shape[0]} points")

    visualize_scene(
        xyz,
        nrm,
        rgb,
        color_by_normals=args.color_by_normals,
        show_arrows=not args.no_arrows,
        max_arrows=args.max_arrows,
    )


if __name__ == "__main__":
    main()
